apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service-stable.yaml
- service-canary.yaml
- ingress.yaml
images:
- name: mmumshad/simple-webapp-color
  newTag: latest
