---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-stable
  template:
    metadata:
      labels:
        app: rollouts-stable
    spec:
      containers:
        - name: rollouts-stable
          image: "nginx"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
  strategy:
#        blueGreen:
#          activeService: rollouts-demo
#          previewService: rollouts-demo-preview
#          autoPromotionEnabled: false
     canary:
       stableService: service-stable
       canaryService: service-canary
       trafficRouting:
        nginx:
          stableIngress: ingress-stable
       steps:
       - setWeight: 20
       - pause: {}
