---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-1
  labels:
    app: canary
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo-1
  template:
    metadata: 
      labels:
        app: rollouts-demo-1
    spec:
      containers:
        - name: rollouts-demo-1
          image: "nginx"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
  strategy:
#     blueGreen:
#       activeService: rollouts-demo
#       previewService: rollouts-demo-preview
     canary: 
       steps:
       - setWeight: 10
       - pause: {}
